language: rust
rust: stable
cache: cargo
env:
  global:
    - NAME=enquirer
    - PKG_CONFIG_ALLOW_CROSS=1
    - SHARD=test
    - EMAIL=pavan.sss1991@gmail.com
jobs:
  allow_failures:
    - env:
        - SHARD=lint
  fast_finish: true
  include:
    - os: osx
      env:
        - TARGET=x86_64-apple-darwin
    - os: linux
      env:
        - TARGET=x86_64-unknown-linux-gnu
    - os: linux
      env:
        - TARGET=i686-unknown-linux-gnu
      addons:
        apt:
          packages:
            - gcc-5-multilib
            - lib32gcc-5-dev
          update: true
      after_deploy: skip
    - os: linux
      env:
        - SHARD=lint
      before_script:
        - rustup component add clippy
        - rustup component add rustfmt
      script:
        - echo "Checking codebase with Clippy release `cargo clippy --version`."
        - cargo clippy --all --profile test
        - cargo fmt -- --check
before_script:
  - rustup target add $TARGET
script:
  - cargo build --target $TARGET
  - cargo test
before_deploy:
  # TODO: Generate man page from clap
  - cargo build --target $TARGET --release
  - export BUILD_NAME=$NAME-$TRAVIS_TAG-$TARGET
  - mkdir target/$BUILD_NAME
  - cp target/$TARGET/release/$NAME LICENSE *.md $NAME.1 target/$BUILD_NAME
  - zip $BUILD_NAME.zip -r target/$BUILD_NAME
deploy:
  edge: true
  provider: releases
  file: ${BUILD_NAME}.zip
  on:
    repo: ${TRAVIS_REPO_SLUG}
    tags: true
    condition: $SHARD = test
